# Generated by Django 6.1.1 on 2026-09-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Districts, Sports, Athletes, Clubs, Tournaments', max_length=100)),
                ('count_display', models.CharField(help_text='e.g. 38, 50+, 1000+, 200+, 100+', max_length=50)),
                ('icon_class', models.CharField(help_text='FontAwesome icon class e.g. fa-solid fa-landmark', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Sorting order')),
            ],
            options={
                'verbose_name': 'Platform Stat',
                'verbose_name_plural': 'Platform Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text='FontAwesome icon class e.g. fa-solid fa-cricket-ball', max_length=100)),
                ('icon_color_class', models.CharField(default='icon-cricket', help_text='CSS color class e.g. icon-cricket, icon-football', max_length=50)),
                ('is_popular', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
            },
        ),
    ]
