# Generated by Django 6.1.1 on 2026-09-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformstat',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='sport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='icon_color_class',
        ),
        migrations.AddField(
            model_name='sport',
            name='color',
            field=models.CharField(default='#16a34a', help_text='Hex code for icon color', max_length=20),
        ),
        migrations.AddField(
            model_name='sport',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platformstat',
            name='count_display',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='platformstat',
            name='icon_class',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='platformstat',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='platformstat',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sport',
            name='icon_class',
            field=models.CharField(help_text='FontAwesome or Lucide icon class', max_length=50),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
