# Generated by Django 6.1.1 on 2026-09-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_alter_platformstat_options_alter_sport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='sport',
            name='category',
            field=models.CharField(default='Team Sports', help_text='e.g. Team Sports, Individual Sports, Racket Sports, Water Sports', max_length=50),
        ),
        migrations.AddField(
            model_name='sport',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='icon_class',
            field=models.CharField(help_text='Bootstrap or FontAwesome icon class', max_length=50),
        ),
    ]
