# Generated by Django 6.1.1 on 2026-09-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_alter_sport_options_sport_category_sport_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image_url', models.CharField(blank=True, help_text='Image URL or thumbnail path', max_length=500, null=True)),
                ('published_date', models.DateField()),
                ('summary', models.TextField(help_text='Short introductory summary (1-2 sentences)')),
                ('content', models.TextField(help_text='Full article body content')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_date'],
            },
        ),
    ]
