# Generated by Django 6.1.1 on 2026-09-06 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('sports_count', models.PositiveIntegerField(default=0)),
                ('athletes_count', models.PositiveIntegerField(default=0)),
                ('clubs_count', models.PositiveIntegerField(default=0)),
                ('tournaments_count', models.PositiveIntegerField(default=0)),
                ('svg_path_id', models.CharField(blank=True, help_text='SVG Path element ID on state map', max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DistrictTopSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('sport_name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_sports', to='sports.district')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('district', 'rank')},
            },
        ),
    ]
