# Generated by Django 6.1.1 on 2026-09-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_district_districttopsport'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='svg_region_id',
            field=models.CharField(blank=True, help_text='Links to SVG map path element ID', max_length=50, null=True),
        ),
    ]
