# Generated by Django 6.1.1 on 2026-09-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_district_svg_region_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='svg_district_id',
            field=models.CharField(blank=True, help_text='Matches SVG path ID (e.g. TN-CO, TN-CH)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='athletes_count',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='district',
            name='clubs_count',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='district',
            name='sports_count',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='district',
            name='tournaments_count',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
