# Generated by Django 6.1.1 on 2026-09-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_district_svg_district_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('audience_target', models.CharField(choices=[('ALL', 'All'), ('PLAYER', 'Players'), ('COACH', 'Coaches'), ('OFFICER', 'Officers')], default='ALL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'News Update',
                'verbose_name_plural': 'News Updates',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PortalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_text', models.TextField(help_text='Vision statement for the platform')),
                ('mission_text', models.TextField(help_text='Mission statement for the platform')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='portal/')),
                ('stadium_image_url', models.CharField(blank=True, default='https://images.unsplash.com/photo-1577223625816-7546f13df25d?q=80&w=1200&auto=format&fit=crop', help_text='URL for stadium or headquarters photo', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Portal Configuration',
                'verbose_name_plural': 'Portal Configuration',
            },
        ),
    ]
