# Generated by Django 6.1.1 on 2026-09-07 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0008_newsupdate_portalconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, default='coaches/default.png', null=True, upload_to='coaches/')),
                ('photo_url', models.CharField(blank=True, help_text='Direct URL for coach avatar image fallback', max_length=500, null=True)),
                ('experience_years', models.PositiveIntegerField(default=5)),
                ('specialization', models.CharField(help_text='e.g. Batting, Defense, Sprint, Coaching, Goal Keeper', max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='sports.district')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='sports.sport')),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
                'ordering': ['-experience_years', 'name'],
            },
        ),
    ]
