# Generated by Django 6.1.1 on 2026-09-08 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0009_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('registration_number', models.CharField(help_text='Society / Trust / Association Reg. No.', max_length=60, unique=True)),
                ('established_year', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('logo', models.ImageField(blank=True, default='club_logos/default.png', upload_to='club_logos/')),
                ('reg_certificate', models.FileField(blank=True, null=True, upload_to='club_certificates/')),
                ('total_members', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='sports.district')),
                ('primary_sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='sports.sport')),
            ],
        ),
    ]
