# Generated by Django 6.1.1 on 2026-09-08 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0010_club'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictSportsOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(default='District Sports & Youth Welfare Officer', max_length=100)),
                ('zone', models.CharField(choices=[('NORTH', 'North Zone'), ('SOUTH', 'South Zone'), ('WEST', 'West Zone'), ('CENTRAL', 'Central Zone')], default='CENTRAL', max_length=20)),
                ('office_address', models.TextField(help_text='e.g., SDAT District Stadium Complex')),
                ('official_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, default='officers/default.png', null=True, upload_to='officers/')),
                ('photo_url', models.CharField(blank=True, help_text='Fallback photo URL', max_length=500, null=True)),
                ('appointed_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer', to='sports.district')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dso_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'District Sports Officer',
                'verbose_name_plural': 'District Sports Officers',
                'ordering': ['district__name'],
            },
        ),
    ]
