# Generated by Django 6.1.1 on 2026-09-08 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0011_districtsportsofficer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organizer_name', models.CharField(max_length=120)),
                ('organizer_contact', models.CharField(max_length=15)),
                ('organizer_email', models.EmailField(max_length=254)),
                ('venue_name', models.CharField(help_text='e.g., VOC Stadium Ground', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('entry_deadline', models.DateField()),
                ('expected_teams', models.PositiveIntegerField(default=8)),
                ('rulebook_doc', models.FileField(blank=True, null=True, upload_to='tournament_docs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending DSO Approval'), ('APPROVED', 'Sanctioned / Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='sports.district')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='sports.sport')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
