# Generated by Django 6.1.1 on 2026-09-08 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0013_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone', models.CharField(max_length=15)),
                ('category', models.CharField(choices=[('SCHOOL', 'School Player'), ('COLLEGE', 'College Player'), ('OPEN', 'Professional / Open')], default='SCHOOL', max_length=20)),
                ('skill_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('DISTRICT', 'District Level'), ('STATE', 'State Level'), ('NATIONAL', 'National Level')], default='BEGINNER', max_length=20)),
                ('club_or_school', models.CharField(blank=True, max_length=150)),
                ('id_proof', models.FileField(blank=True, help_text='Aadhaar or School ID', null=True, upload_to='athlete_docs/')),
                ('profile_photo', models.ImageField(blank=True, default='default_player.png', null=True, upload_to='athlete_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='sports.district')),
                ('primary_sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='sports.sport')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Athlete',
                'verbose_name_plural': 'Athletes',
                'ordering': ['-created_at'],
            },
        ),
    ]
