# Generated by Django 6.1.1 on 2026-09-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0014_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='age_category',
            field=models.CharField(choices=[('U14', 'Under 14'), ('U17', 'Under 17'), ('U19', 'Under 19'), ('OPEN', 'Open Senior')], default='U17', max_length=20),
        ),
        migrations.AddField(
            model_name='athlete',
            name='emis_id',
            field=models.CharField(blank=True, help_text='16-Digit EMIS Student Identifier', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='qr_token',
            field=models.CharField(blank=True, help_text='Unique QR Token for digital pass', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('CLEARED', 'Cleared / Pass Issued'), ('FLAGGED', 'Flagged / Disqualified')], default='CLEARED', max_length=20),
        ),
    ]
