# Generated by Django 6.1.1 on 2026-09-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0015_athlete_age_category_athlete_emis_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='description',
            field=models.TextField(blank=True, help_text='Overview of sport governance and district presence', null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='logo_url',
            field=models.CharField(blank=True, help_text='Official sport logo image URL', max_length=500, null=True),
        ),
    ]
