# Generated by Django 6.1.1 on 2026-09-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0016_sport_description_sport_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinisterControlSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_districts', models.PositiveIntegerField(default=38, help_text='Total Districts Managed')),
                ('target_schools', models.PositiveIntegerField(default=4120, help_text='Active State Schools')),
                ('verified_pets', models.PositiveIntegerField(default=3840, help_text='Verified PET Teachers')),
                ('budget_allocation_cr', models.DecimalField(decimal_places=2, default=50.0, help_text='State Budget Allocation (₹ in Crores)', max_digits=10)),
                ('target_athletes', models.PositiveIntegerField(default=15000, help_text='Target Athlete Registrations')),
                ('north_gold_medals', models.PositiveIntegerField(default=42)),
                ('north_hq', models.CharField(default='Chennai Complex', max_length=150)),
                ('north_districts', models.PositiveIntegerField(default=9)),
                ('west_gold_medals', models.PositiveIntegerField(default=48)),
                ('west_hq', models.CharField(default='Coimbatore Complex', max_length=150)),
                ('west_districts', models.PositiveIntegerField(default=10)),
                ('central_gold_medals', models.PositiveIntegerField(default=36)),
                ('central_hq', models.CharField(default='Tiruchirappalli Complex', max_length=150)),
                ('central_districts', models.PositiveIntegerField(default=9)),
                ('south_gold_medals', models.PositiveIntegerField(default=39)),
                ('south_hq', models.CharField(default='Madurai Complex', max_length=150)),
                ('south_districts', models.PositiveIntegerField(default=10)),
                ('auto_verify_pet_emis', models.BooleanField(default=True, help_text='Enable Automatic PET EMIS Verification')),
                ('tournament_sanction_mode', models.CharField(choices=[('AUTO', 'Auto Sanction Tournaments'), ('OFFICER_REVIEW', 'DSO Officer Review Required'), ('MINISTER_SIGNOFF', 'Sports Minister Approval Required')], default='OFFICER_REVIEW', max_length=25)),
                ('cm_trophy_registration_open', models.BooleanField(default=True, help_text='CM Trophy Registrations Active')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Portal Maintenance Mode Flag')),
                ('gold_medal_pts', models.PositiveIntegerField(default=50, help_text='Points per Gold Medal')),
                ('silver_medal_pts', models.PositiveIntegerField(default=30, help_text='Points per Silver Medal')),
                ('bronze_medal_pts', models.PositiveIntegerField(default=10, help_text='Points per Bronze Medal')),
                ('participation_bonus_pts', models.PositiveIntegerField(default=5, help_text='Bonus points per district participant')),
                ('state_announcement_title', models.CharField(blank=True, default='TN Sports Policy 2026: Executive Infrastructure Sanction', max_length=255)),
                ('state_announcement_body', models.TextField(blank=True, default='₹50 Cr State Budget allocated for rural stadium upgrade, synthetic track installation, and high-performance athlete scholarships.')),
                ('portal_live_ticker', models.CharField(blank=True, default='Welcome to Tamil Nadu Sports Development Authority Portal • Chief Minister Trophy 2026 District Trials Open • Verify PET & School Credentials.', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Minister Executive Control Setting',
                'verbose_name_plural': 'Minister Executive Control Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ['name']},
        ),
    ]
