# Generated by Django 6.1.1 on 2026-09-15 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0017_ministercontrolsetting_alter_sport_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='e.g. NORTH, WEST, CENTRAL, SOUTH', max_length=20, unique=True)),
                ('headquarters', models.CharField(default='District Stadium Complex', max_length=150)),
                ('gold_medals_target', models.PositiveIntegerField(default=40)),
                ('color', models.CharField(default='#2563eb', help_text='Hex code or theme color', max_length=20)),
                ('bg_gradient', models.CharField(default='from-blue-600 to-indigo-700', help_text='Tailwind CSS gradient class string', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts', to='sports.zone'),
        ),
        migrations.CreateModel(
            name='DistrictSubZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Madurai Urban Sub-Zone, Coimbatore North Sub-Zone', max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('headquarters_or_venue', models.CharField(blank=True, help_text='Sub-Zone Stadium or Office Venue', max_length=200)),
                ('contact_officer_name', models.CharField(blank=True, help_text='Sub-Zone Officer or Coordinator Name', max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('athletes_count', models.PositiveIntegerField(default=0)),
                ('clubs_count', models.PositiveIntegerField(default=0)),
                ('schools_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_zones', to='sports.district')),
            ],
            options={
                'verbose_name': 'District Sub-Zone',
                'verbose_name_plural': 'District Sub-Zones',
                'ordering': ['name'],
                'unique_together': {('district', 'name')},
            },
        ),
    ]
