# Generated by Django 6.1.1 on 2026-09-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0018_zone_district_zone_districtsubzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtsubzone',
            name='covered_places',
            field=models.TextField(blank=True, help_text='Covered places, taluks, or local areas under this sub-zone (comma-separated or listed)', null=True),
        ),
    ]
