# Generated by Django 6.1.1 on 2026-09-15 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0019_districtsubzone_covered_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtsubzone',
            name='covered_places',
            field=models.TextField(blank=True, help_text='Covered places, taluks, or local areas summary', null=True),
        ),
        migrations.CreateModel(
            name='DistrictPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Place, Taluk, Block, or Area Name', max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='sports.district')),
            ],
            options={
                'verbose_name': 'District Place / Taluk',
                'verbose_name_plural': 'District Places / Taluks',
                'ordering': ['name'],
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.AddField(
            model_name='districtsubzone',
            name='places',
            field=models.ManyToManyField(blank=True, help_text='Selectable places under this sub-zone', related_name='sub_zones', to='sports.districtplace'),
        ),
    ]
