# Generated by Django 6.1.1 on 2026-09-15 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0020_alter_districtsubzone_covered_places_districtplace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='sports_arti_slug_a59bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_date'], name='sports_arti_publish_1ce766_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_published'], name='sports_arti_is_publ_d93476_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['district', 'primary_sport'], name='sports_athl_distric_49f1cf_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['category'], name='sports_athl_categor_ee00e1_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['verification_status'], name='sports_athl_verific_58f9c7_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['emis_id'], name='sports_athl_emis_id_6a4578_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['created_at'], name='sports_athl_created_fc50da_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['slug'], name='sports_club_slug_e4e571_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['district', 'primary_sport'], name='sports_club_distric_93714d_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['status'], name='sports_club_status_8522f1_idx'),
        ),
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['district', 'sport'], name='sports_coac_distric_a6d6d6_idx'),
        ),
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['is_active'], name='sports_coac_is_acti_24b048_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['submitted_at'], name='sports_cont_submitt_315b67_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_resolved'], name='sports_cont_is_reso_120017_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['slug'], name='sports_dist_slug_061786_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['zone'], name='sports_dist_zone_id_b973b3_idx'),
        ),
        migrations.AddIndex(
            model_name='districtplace',
            index=models.Index(fields=['district', 'slug'], name='sports_dist_distric_da6bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='districtsportsofficer',
            index=models.Index(fields=['district'], name='sports_dist_distric_b6a719_idx'),
        ),
        migrations.AddIndex(
            model_name='districtsportsofficer',
            index=models.Index(fields=['zone'], name='sports_dist_zone_5c6307_idx'),
        ),
        migrations.AddIndex(
            model_name='districtsportsofficer',
            index=models.Index(fields=['is_active'], name='sports_dist_is_acti_0dbcd8_idx'),
        ),
        migrations.AddIndex(
            model_name='districtsubzone',
            index=models.Index(fields=['district', 'slug'], name='sports_dist_distric_ce12f3_idx'),
        ),
        migrations.AddIndex(
            model_name='districtsubzone',
            index=models.Index(fields=['is_active'], name='sports_dist_is_acti_789a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='districttopsport',
            index=models.Index(fields=['district', 'rank'], name='sports_dist_distric_e05d07_idx'),
        ),
        migrations.AddIndex(
            model_name='newsupdate',
            index=models.Index(fields=['date'], name='sports_news_date_1a17cf_idx'),
        ),
        migrations.AddIndex(
            model_name='newsupdate',
            index=models.Index(fields=['audience_target'], name='sports_news_audienc_42cc87_idx'),
        ),
        migrations.AddIndex(
            model_name='newsupdate',
            index=models.Index(fields=['is_active'], name='sports_news_is_acti_64c1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='platformstat',
            index=models.Index(fields=['order'], name='sports_plat_order_45bfb8_idx'),
        ),
        migrations.AddIndex(
            model_name='sport',
            index=models.Index(fields=['slug'], name='sports_spor_slug_ca78a5_idx'),
        ),
        migrations.AddIndex(
            model_name='sport',
            index=models.Index(fields=['category'], name='sports_spor_categor_e9522a_idx'),
        ),
        migrations.AddIndex(
            model_name='sport',
            index=models.Index(fields=['is_popular'], name='sports_spor_is_popu_a11dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['district', 'sport'], name='sports_tour_distric_769aac_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status'], name='sports_tour_status_052fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['start_date'], name='sports_tour_start_d_26cc07_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['code'], name='sports_zone_code_8c7199_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['order'], name='sports_zone_order_e9e25b_idx'),
        ),
    ]
