# Generated by Django 6.1.1 on 2026-09-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0021_alter_club_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministercontrolsetting',
            name='implementation_plan_budget_cr',
            field=models.DecimalField(decimal_places=2, default=250.0, help_text='Total Approved Implementation Budget (₹ Cr)', max_digits=10),
        ),
        migrations.AddField(
            model_name='ministercontrolsetting',
            name='implementation_plan_image',
            field=models.CharField(blank=True, default='/static/images/minister_masterplan.png', max_length=500),
        ),
        migrations.AddField(
            model_name='ministercontrolsetting',
            name='implementation_plan_progress_percent',
            field=models.PositiveIntegerField(default=68, help_text='Overall Plan Completion %'),
        ),
        migrations.AddField(
            model_name='ministercontrolsetting',
            name='implementation_plan_secondary_image',
            field=models.CharField(blank=True, default='/static/images/minister_academy_plan.png', max_length=500),
        ),
        migrations.AddField(
            model_name='ministercontrolsetting',
            name='implementation_plan_status',
            field=models.CharField(blank=True, default='Phase 2 Execution Active', max_length=100),
        ),
        migrations.AddField(
            model_name='ministercontrolsetting',
            name='implementation_plan_summary',
            field=models.TextField(blank=True, default='Comprehensive 4-Phase Executive Roadmap for Olympic-Grade Synthetic Track Upgrades, 38 District Sports Academies, Biomechanical Science Hubs, & Grassroots Athlete Pipeline.'),
        ),
        migrations.AddField(
            model_name='ministercontrolsetting',
            name='implementation_plan_target_year',
            field=models.CharField(blank=True, default='2026 - 2030', max_length=50),
        ),
        migrations.AddField(
            model_name='ministercontrolsetting',
            name='implementation_plan_title',
            field=models.CharField(blank=True, default='Statewide Sports Infrastructure & High-Performance Implementation Plan 2026-2030', max_length=255),
        ),
    ]
