# Generated by Django 6.1.1 on 2026-10-01 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0022_ministercontrolsetting_implementation_plan_budget_cr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending DSO Approval'), ('DSO_APPROVED', 'Approved by DSO - Pending Minister News Approval'), ('APPROVED', 'Sanctioned & Published in State News'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15),
        ),
        migrations.CreateModel(
            name='DSOTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_reference', models.CharField(help_text='e.g. G.O. Ms. No. 154/2026 Sports Dept', max_length=100)),
                ('reason', models.TextField(blank=True, help_text='Transfer Rationale / Reassignment Details', null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('from_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='sports.district')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='sports.districtsportsofficer')),
                ('to_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='sports.district')),
            ],
            options={
                'verbose_name': 'DSO Transfer Log',
                'verbose_name_plural': 'DSO Transfer Logs',
                'ordering': ['-transferred_at'],
                'indexes': [models.Index(fields=['officer'], name='sports_dsot_officer_de11ce_idx'), models.Index(fields=['transferred_at'], name='sports_dsot_transfe_d893c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='MinisterDSOOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Government Order Ref, e.g. G.O. Ms. No. 89/2026', max_length=60)),
                ('title', models.CharField(help_text='Subject / Directive Title', max_length=255)),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority Directive'), ('URGENT', 'Urgent Action Required'), ('ROUTINE', 'Routine Directive')], default='HIGH', max_length=20)),
                ('instruction', models.TextField(help_text='Detailed Order text / instruction from Sports Minister')),
                ('target_date', models.DateField(blank=True, help_text='Compliance deadline', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Issued - Awaiting Compliance'), ('IN_PROGRESS', 'Compliance Underway'), ('COMPLETED', 'Complied & Verified')], default='PENDING', max_length=20)),
                ('compliance_report', models.TextField(blank=True, help_text='DSO compliance feedback text', null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, help_text='Target District', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minister_orders', to='sports.district')),
                ('dso', models.ForeignKey(blank=True, help_text='Target DSO (Leave blank for statewide order)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minister_orders', to='sports.districtsportsofficer')),
            ],
            options={
                'verbose_name': 'Minister Executive Order to DSO',
                'verbose_name_plural': 'Minister Executive Orders to DSOs',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['dso', 'status'], name='sports_mini_dso_id_0e039a_idx'), models.Index(fields=['issued_at'], name='sports_mini_issued__6ab5f7_idx')],
            },
        ),
    ]
