# Generated by Django 6.1.1 on 2026-10-01 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0023_alter_tournament_status_dsotransferlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSOTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('TRANSFER', 'District Transfer Request'), ('REASSIGNMENT', 'Reassignment / Duty Change Request')], default='TRANSFER', max_length=20)),
                ('preferred_duty', models.CharField(blank=True, help_text='Target duty/zone/responsibility if Reassignment Request', max_length=255, null=True)),
                ('reason', models.TextField(help_text='Detailed reason / rationale for transfer or reassignment')),
                ('additional_remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Minister Review'), ('APPROVED', 'Approved & Order Issued'), ('REJECTED', 'Rejected by Minister')], default='PENDING', max_length=20)),
                ('minister_remarks', models.TextField(blank=True, help_text='Remarks from Sports Minister upon decision', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='sports.districtsportsofficer')),
                ('preferred_district', models.ForeignKey(blank=True, help_text='Target district if Transfer Request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to='sports.district')),
            ],
            options={
                'verbose_name': 'DSO Transfer & Reassignment Request',
                'verbose_name_plural': 'DSO Transfer & Reassignment Requests',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['officer', 'status'], name='sports_dsot_officer_c499a9_idx'), models.Index(fields=['submitted_at'], name='sports_dsot_submitt_f5a435_idx')],
            },
        ),
    ]
