# Generated by Django 6.1.1 on 2026-10-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0024_dsotransferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministercontrolsetting',
            name='coach_can_view_athlete_contacts',
            field=models.BooleanField(default=False, help_text='Allow coaches to view athlete personal contact details'),
        ),
        migrations.AddField(
            model_name='ministercontrolsetting',
            name='dso_can_edit_subzones',
            field=models.BooleanField(default=True, help_text='Allow DSOs to manage district sub-zones & taluks'),
        ),
        migrations.AddField(
            model_name='ministercontrolsetting',
            name='dso_can_view_statewide_rankings',
            field=models.BooleanField(default=True, help_text='Allow DSOs to view statewide leaderboard & analytics'),
        ),
        migrations.AddField(
            model_name='ministercontrolsetting',
            name='dso_can_view_transfer_history',
            field=models.BooleanField(default=True, help_text='Allow DSOs to view full transfer audit log'),
        ),
        migrations.AddField(
            model_name='ministercontrolsetting',
            name='pet_can_verify_squads',
            field=models.BooleanField(default=True, help_text='Allow PET teachers to authorize EMIS student selection squads'),
        ),
        migrations.AddField(
            model_name='ministercontrolsetting',
            name='public_can_view_coach_directory',
            field=models.BooleanField(default=True, help_text='Allow public to search state certified coach directory'),
        ),
        migrations.AddField(
            model_name='ministercontrolsetting',
            name='public_can_view_leaderboard',
            field=models.BooleanField(default=True, help_text='Allow public to view district standings'),
        ),
        migrations.AddField(
            model_name='ministercontrolsetting',
            name='public_can_view_tournaments',
            field=models.BooleanField(default=True, help_text='Allow public to view sanctioned tournaments'),
        ),
    ]
