# Generated by Django 6.1.1 on 2026-10-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0025_ministercontrolsetting_coach_can_view_athlete_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='age_condition',
            field=models.CharField(default='Open Category (All Ages)', help_text='e.g. Under 14, Under 17, Under 25, Open 18+, Masters 35+', max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='level_category',
            field=models.CharField(choices=[('SCHOOL', 'School Level'), ('COLLEGE', 'College / University Level'), ('GENERAL', 'General / Open Age Level')], default='GENERAL', help_text='School, College or General Open Category', max_length=20),
        ),
    ]
