# Generated by Django 6.1.1 on 2026-10-02 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0026_tournament_age_condition_tournament_level_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateSportsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Scheme / Plan Title, e.g. CM Trophy Talent Excellence Scheme 2026', max_length=255)),
                ('plan_code', models.CharField(help_text='e.g. TN-SP-2026-001', max_length=50, unique=True)),
                ('action_type', models.CharField(choices=[('NEW_PLAN', 'New State Plan Implementation'), ('UPGRADE_PLAN', 'Upgrade Existing Plan')], default='NEW_PLAN', max_length=20)),
                ('category', models.CharField(default='Infrastructure & Talent', help_text='e.g. Infrastructure, Grassroots Talent, Athlete Support', max_length=100)),
                ('existing_plan_name', models.CharField(blank=True, help_text='Name of existing plan if upgrading', max_length=255, null=True)),
                ('budget_allocated', models.CharField(default='₹15 Crores', help_text='Budget Allocation string', max_length=100)),
                ('target_districts_count', models.PositiveIntegerField(default=38, help_text='Number of target districts')),
                ('objectives', models.TextField(help_text='Key objectives & rollout directives')),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed Plan'), ('SANCTIONED', 'Sanctioned by Minister'), ('IN_PROGRESS', 'Implementation Underway'), ('COMPLETED', 'Fully Implemented Across State')], default='SANCTIONED', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=35, help_text='Implementation progress (0-100%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'State Sports Plan',
                'verbose_name_plural': 'State Sports Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ministerdsoorder',
            name='budget_allocated',
            field=models.CharField(blank=True, help_text='Budget allocation e.g. ₹20 Crores', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ministerdsoorder',
            name='order_type',
            field=models.CharField(choices=[('DIRECTIVE', 'General Executive Directive'), ('UPGRADE_PLAN', 'Upgrade Existing State Plan'), ('NEW_PLAN', 'Implement New State Plan')], default='DIRECTIVE', max_length=30),
        ),
        migrations.AddField(
            model_name='ministerdsoorder',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sports.statesportsplan'),
        ),
    ]
