from django.urls import path
from .views import (
    home_view, index, sports_list_view, sports,
    news_list_view, news_detail_view, news,
    districts_view, districts, district_detail_api, district_detail_partial,
    athletes, players, clubs, clubs_view, tournaments, tournaments_view,
    login_view, logout_view,
    portal_home_view, role_login_view, officer_login_view, collector_login_view, minister_login_view,
    coaches_list_view, coach_contact_view, coach_register_view, coach_dashboard_view,
    dso_dashboard_view, update_club_status, sanction_tournament,
    dso_tournament_action, contact_view, athlete_register_view, athlete_dashboard_view,
    admin_dashboard_view, minister_dashboard_view, update_minister_keys_view, collector_dashboard_view,
    api_emis_verify, api_session_keepalive,
    update_zone_view, save_subzone_view, delete_subzone_view, assign_dso_view, export_dso_database_csv,
    export_tournaments_csv, export_athletes_csv, publish_news_view, minister_tournament_news_action,
    issue_minister_order_view, transfer_dso_view, delete_minister_order_view,
    submit_dso_request_view, minister_action_dso_request_view, toggle_user_status_view
)


urlpatterns = [
    path('', portal_home_view, name='portal_home'),
    path('portal/', portal_home_view, name='portal_home_alt'),
    path('portal/admin/', admin_dashboard_view, name='custom_admin_dashboard'),
    path('portal/admin/dashboard/', admin_dashboard_view, name='custom_admin_dashboard_portal'),
    path('portal/minister/', minister_dashboard_view, name='minister_dashboard'),
    path('coach/dashboard/', coach_dashboard_view, name='coach_dashboard'),
    path('portal/minister/tournaments/<int:tournament_id>/<str:action>/', minister_tournament_news_action, name='minister_tournament_news_action'),
    path('portal/minister/dso/assign/', assign_dso_view, name='assign_dso'),
    path('portal/minister/dso/transfer/', transfer_dso_view, name='transfer_dso'),
    path('portal/minister/dso-request/<int:request_id>/<str:action>/', minister_action_dso_request_view, name='minister_dso_request_action'),
    path('portal/minister/user/<int:user_id>/toggle-status/', toggle_user_status_view, name='toggle_user_status'),
    path('portal/minister/order/issue/', issue_minister_order_view, name='issue_minister_order'),
    path('portal/minister/order/<int:order_id>/delete/', delete_minister_order_view, name='delete_minister_order'),
    path('portal/minister/dso/export-csv/', export_dso_database_csv, name='export_dso_csv'),
    path('portal/minister/export/tournaments-csv/', export_tournaments_csv, name='export_tournaments_csv'),
    path('portal/minister/export/athletes-csv/', export_athletes_csv, name='export_athletes_csv'),
    path('portal/minister/update-keys/', update_minister_keys_view, name='update_minister_keys'),
    path('portal/minister/zone/<int:zone_id>/edit/', update_zone_view, name='update_zone'),
    path('portal/minister/news/publish/', publish_news_view, name='publish_news'),
    path('portal/collector/', collector_dashboard_view, name='collector_dashboard'),
    path('portal/collector/subzone/save/', save_subzone_view, name='save_subzone'),
    path('portal/collector/subzone/<int:subzone_id>/delete/', delete_subzone_view, name='delete_subzone'),

    path('api/emis/verify/', api_emis_verify, name='api_emis_verify'),
    path('api/session/keepalive/', api_session_keepalive, name='api_session_keepalive'),
    path('home/', home_view, name='home'),
    path('index/', index, name='index'),
    path('login/', login_view, name='login'),
    path('login/officer/', officer_login_view, name='officer_login'),
    path('login/collector/', collector_login_view, name='collector_login'),
    path('login/minister/', minister_login_view, name='minister_login'),
    path('login/<str:role>/', role_login_view, name='role_login'),
    path('logout/', logout_view, name='logout'),
    path('contact/', contact_view, name='contact'),
    path('sports/', sports_list_view, name='sports'),
    path('sports/contact/', contact_view, name='sports_contact'),
    path('news/', news_list_view, name='news'),
    path('news/feed/', news_list_view, name='news_list'),
    path('news/<slug:slug>/', news_detail_view, name='news_detail'),
    path('districts/', districts_view, name='districts'),
    path('districts/<slug:slug>/partial/', district_detail_partial, name='district_detail_partial'),
    path('api/districts/<slug:slug>/', district_detail_api, name='district_api'),
    path('api/districts/stats/<slug:slug>/', district_detail_api, name='district_stats_api'),
    path('players/', players, name='players'),
    path('athletes/', players, name='athletes'),
    path('athlete/register/', athlete_register_view, name='athlete_register'),
    path('athlete/dashboard/', athlete_dashboard_view, name='athlete_dashboard'),
    path('clubs/', clubs, name='clubs'),
    path('tournaments/', tournaments_view, name='tournaments'),
    path('coaches/', coaches_list_view, name='coaches'),
    path('coaches/list/', coaches_list_view, name='coaches_list'),
    path('coaches/register/', coach_register_view, name='coach_register'),
    path('coaches/<int:pk>/contact/', coach_contact_view, name='coach_contact'),
    path('portal/dso/dashboard/', dso_dashboard_view, name='dso_dashboard'),
    path('portal/dso/request/submit/', submit_dso_request_view, name='submit_dso_request'),
    path('portal/dso/clubs/<int:club_id>/<str:action>/', update_club_status, name='club_approval'),
    path('portal/dso/tournaments/<int:tournament_id>/<str:action>/', dso_tournament_action, name='dso_tournament_action'),
    path('portal/dso/tournaments/sanction/', sanction_tournament, name='sanction_tournament'),
]



