"""
Django settings for soprts project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file if available
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
    load_dotenv(BASE_DIR.parent / '.env')
except ImportError:
    pass

try:
    import dj_database_url
except ImportError:
    dj_database_url = None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-7fb057@-ql+2_!o9a80ohm2x#ipe#_+14q#sgcda)%qqmn-6x*')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', '*').split(',') if host.strip()]

# CSRF trusted origins for production domains (comma-separated, e.g., https://example.com)
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'sports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'soprts.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'sports' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'soprts.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Connection pooling & persistent connections
# Production default: 600s (re-uses connections across requests, reducing handshake latency)
# Development default: 0s (closes connections immediately)
DB_CONN_MAX_AGE = int(os.getenv('DB_CONN_MAX_AGE', '600' if not DEBUG else '0'))
DB_CONN_HEALTH_CHECKS = os.getenv('DB_CONN_HEALTH_CHECKS', 'True').lower() in ('true', '1', 'yes')
DB_SSLMODE = os.getenv('DB_SSLMODE', '').strip()
DB_CONNECT_TIMEOUT = os.getenv('DB_CONNECT_TIMEOUT', '').strip()
DB_DISABLE_SERVER_SIDE_CURSORS = os.getenv('DB_DISABLE_SERVER_SIDE_CURSORS', 'False').lower() in ('true', '1', 'yes')

DATABASE_URL = os.getenv('DATABASE_URL', '').strip()

# Check if discrete database parameters are explicitly defined in environment
HAS_EXPLICIT_DB = bool(
    os.getenv('DB_NAME') or os.getenv('POSTGRES_DB') or
    os.getenv('DB_HOST') or os.getenv('POSTGRES_HOST') or
    os.getenv('DB_ENGINE')
)

if DATABASE_URL and dj_database_url:
    # 1. DYNAMIC SWITCHING: When DATABASE_URL is provided in environment (PostgreSQL, SQLite, MySQL, etc.)
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=DB_CONN_MAX_AGE,
            conn_health_checks=DB_CONN_HEALTH_CHECKS,
        )
    }
elif HAS_EXPLICIT_DB:
    # 2. DISCRETE CONFIGURATION: When discrete database variables are set
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.getenv('DB_NAME', os.getenv('POSTGRES_DB', 'sports_db')),
            'USER': os.getenv('DB_USER', os.getenv('POSTGRES_USER', 'postgres')),
            'PASSWORD': os.getenv('DB_PASSWORD', os.getenv('POSTGRES_PASSWORD', 'root')),
            'HOST': os.getenv('DB_HOST', os.getenv('POSTGRES_HOST', '127.0.0.1')),
            'PORT': os.getenv('DB_PORT', os.getenv('POSTGRES_PORT', '5432')),
            'CONN_MAX_AGE': DB_CONN_MAX_AGE,
            'CONN_HEALTH_CHECKS': DB_CONN_HEALTH_CHECKS,
        }
    }
else:
    # 3. ZERO-CONFIG LOCAL FALLBACK: When no DB URL is provided, dynamically switch to SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Apply PostgreSQL-specific tuning ONLY if the active backend is PostgreSQL
active_engine = DATABASES['default'].get('ENGINE', '')
if 'postgresql' in active_engine:
    db_options = DATABASES['default'].setdefault('OPTIONS', {})

    if DB_SSLMODE:
        db_options['sslmode'] = DB_SSLMODE
    elif not DEBUG:
        host = DATABASES['default'].get('HOST', '')
        if host and host not in ('localhost', '127.0.0.1'):
            db_options.setdefault('sslmode', 'require')

    if DB_CONNECT_TIMEOUT:
        db_options['connect_timeout'] = int(DB_CONNECT_TIMEOUT)

    if DB_DISABLE_SERVER_SIDE_CURSORS:
        DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'sports' / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Session Security & Automatic Idle Expiration
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 1800  # 30 Minutes maximum idle session lifespan
SESSION_SAVE_EVERY_REQUEST = True  # Resets the session timer on active requests
SESSION_COOKIE_HTTPONLY = True

# Authentication Redirect Settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'portal_home'
LOGOUT_REDIRECT_URL = 'portal_home'


